/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://qi2vrijv2fantgt6k2lrzdlo3u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7nqylvafnvh5hkddd2lwmyu45y",
    "aws_cognito_identity_pool_id": "us-east-1:4e883003-a52d-43fa-bfed-e87930edf4f3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PyTwcqosL",
    "aws_user_pools_web_client_id": "5o6rll3pvfm03ic3fetf0fgu79",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
